---
author: Recai Oktaş
description: Folyolar
email: roktas@bil.omu.edu.tr
url: fo.roktas.me
domain: roktas.me
brand: '57'
intro: ''
googleanalytics: UA-30559967-1
googleplus: '101391045956417989620'
landslide: /usr/bin/landslide
css: _/default.css _/local.css
js: _/default.js
